#Application URLs
#url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login


#Browser selection
browser=chrome


#credentials
userName=admin
passwaord=admin123


#Waits (in seconds)
implicitWait=10
explicitwait=30



#local installed app admin username & password
localUser=admin
localPassword=Manish@880
url=http://localhost/OrangeHRM/orangehrm-5.8/web/index.php/auth/login
sqlURL=http://localhost/phpmyadmin/